project:
  type: website
  output-dir: docs

website:
  title: "PARSE Health"
  navbar:
    left:
      - href: index.qmd
        text: App


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



